"""Add platform_author_id and likes_count to comments

Revision ID: 84874a4eac9f
Revises: e6f48a2dcd54
Create Date: 2026-02-25 17:35:48.194124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84874a4eac9f'
down_revision = 'e6f48a2dcd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_author_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes_count')
        batch_op.drop_column('platform_author_id')

    # ### end Alembic commands ###
